const MF = (() => {
 const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Amman',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const id=()=>crypto.randomUUID();
 const money=x=>Math.round(Number(x)*1000);
 const qty=x=>Math.round(Number(x)*1000);
 const fresh=()=>({schema:1,store:'مؤمن فريش',currency:'JOD',revision:0,products:[],sales:[],purchases:[],expenses:[],waste:[],settlements:[],settings:{talabatPct:0,cardPct:0},updatedAt:new Date().toISOString()});
 const int=(n,min=0)=>Number.isSafeInteger(n)&&n>=min&&n<=1e12;
 const need=(x,m)=>{if(!x)throw Error(m);};
 function validate(s){
  need(s&&s.schema===1&&s.store==='مؤمن فريش'&&s.currency==='JOD'&&int(s.revision),'ملف حسابات غير صالح');
  for(const k of ['products','sales','purchases','expenses','waste','settlements'])need(Array.isArray(s[k])&&s[k].length<=50000,'ملف كبير أو ناقص');
  const ids=new Set();for(const p of s.products){need(p&&typeof p.id==='string'&&!ids.has(p.id)&&typeof p.name==='string'&&p.name.trim().length>0&&p.name.length<=80&&['kg','piece'].includes(p.unit)&&int(p.price)&&int(p.stock)&&int(p.value)&&typeof p.priceDate==='string','بيانات صنف غير صالحة');need(p.unit==='kg'||p.stock%1000===0,'عدد الحبات غير صالح');ids.add(p.id);}
  need(s.settings&&Number.isFinite(s.settings.talabatPct)&&s.settings.talabatPct>=0&&s.settings.talabatPct<=100&&Number.isFinite(s.settings.cardPct)&&s.settings.cardPct>=0&&s.settings.cardPct<=100,'نسبة العمولة غير صالحة');
  const records=new Set();for(const k of ['sales','purchases','expenses','waste','settlements'])for(const r of s[k]){need(r&&typeof r.id==='string'&&!records.has(r.id)&&/^\d{4}-\d{2}-\d{2}$/.test(r.date),'سجل غير صالح');records.add(r.id);}
  for(const r of s.sales){need(int(r.total)&&int(r.cost)&&int(r.fee)&&r.fee<=r.total&&int(r.net)&&r.net===r.total-r.fee&&['cash','visa','master','talabat'].includes(r.payment)&&Array.isArray(r.lines)&&r.lines.length>0,'فاتورة غير صالحة');let total=0,cost=0;for(const l of r.lines){need(ids.has(l.productId)&&int(l.q,1)&&int(l.price)&&int(l.total)&&int(l.cost)&&typeof l.name==='string'&&['kg','piece'].includes(l.unit)&&l.total===Math.round(l.price*l.q/1000),'بند فاتورة غير صالح');total+=l.total;cost+=l.cost;}need(total===r.total&&cost===r.cost,'مجموع الفاتورة غير صالح');}
  for(const r of s.purchases)need(ids.has(r.productId)&&int(r.q,1)&&int(r.total)&&['cash','visa','master'].includes(r.payment)&&typeof r.name==='string','شراء غير صالح');
  for(const r of s.expenses)need(int(r.total,1)&&typeof r.note==='string'&&['cash','visa','master'].includes(r.payment),'مصروف غير صالح');
  for(const r of s.waste)need(ids.has(r.productId)&&int(r.q,1)&&int(r.cost)&&typeof r.name==='string','تالف غير صالح');
  const settled=new Set();for(const r of s.settlements){const sale=s.sales.find(x=>x.id===r.saleId);need(sale&&sale.payment==='talabat'&&!sale.voided&&!settled.has(r.saleId)&&r.total===sale.net,'تسوية طلبات غير صالحة');settled.add(r.saleId);}
  return s;
 }
 function addProduct(s,name,unit,price){name=String(name).trim();need(name&&name.length<=80,'أدخل اسم الصنف');need(!s.products.some(p=>p.name===name),'الصنف موجود بالفعل');need(['kg','piece'].includes(unit)&&int(price),'السعر أو الوحدة غير صحيح');s.products.push({id:id(),name,unit,price,priceDate:day(),stock:0,value:0});}
 function quantity(p,q){need(int(q,1)&& (p.unit==='kg'||q%1000===0),'أدخل كمية صحيحة؛ الحبة لا تقبل كسرًا');}
 function buy(s,productId,q,total,payment,supplier){const p=s.products.find(x=>x.id===productId);need(p,'اختر الصنف');quantity(p,q);need(int(total,1)&&['cash','visa','master'].includes(payment),'أدخل التكلفة وطريقة الدفع');p.stock+=q;p.value+=total;s.purchases.push({id:id(),date:day(),productId,q,total,payment,supplier:String(supplier||'').slice(0,100),name:p.name});}
 function sell(s,cart,payment,pct,reference){need(cart.length&&['cash','visa','master','talabat'].includes(payment),'الفاتورة فارغة');need(Number.isFinite(pct)&&pct>=0&&pct<=100,'نسبة العمولة غير صحيحة');const seen=new Set();const lines=cart.map(l=>{need(!seen.has(l.productId),'الصنف مكرر');seen.add(l.productId);const p=s.products.find(x=>x.id===l.productId);need(p,'الصنف غير موجود');quantity(p,l.q);need(p.stock>=l.q,'المخزون لا يكفي: '+p.name);need(int(l.price),'سعر غير صالح');const cost=l.q===p.stock?p.value:Math.round(p.value*l.q/p.stock);const total=Math.round(l.price*l.q/1000);return {productId:p.id,name:p.name,unit:p.unit,q:l.q,price:l.price,total,cost};});const total=lines.reduce((a,l)=>a+l.total,0);need(total>0,'قيمة الفاتورة يجب أن تكون أكبر من صفر');const fee=Math.round(total*pct/100);const sale={id:id(),number:s.sales.length+1,date:day(),time:new Date().toISOString(),lines,total,cost:lines.reduce((a,l)=>a+l.cost,0),fee,net:total-fee,payment,reference:String(reference||'').slice(0,100),voided:false};for(const l of lines){const p=s.products.find(x=>x.id===l.productId);p.stock-=l.q;p.value-=l.cost;}s.sales.push(sale);return sale;}
 function waste(s,productId,q,note){const p=s.products.find(x=>x.id===productId);need(p,'اختر صنفًا');quantity(p,q);need(p.stock>=q,'المخزون لا يكفي');const cost=q===p.stock?p.value:Math.round(p.value*q/p.stock);p.stock-=q;p.value-=cost;s.waste.push({id:id(),date:day(),productId,name:p.name,q,cost,note:String(note||'').slice(0,100)});}
 function voidSale(s,saleId){const r=s.sales.find(x=>x.id===saleId);need(r&&!r.voided,'الفاتورة ملغاة أو غير موجودة');need(!s.settlements.some(x=>x.saleId===saleId),'لا يمكن إلغاء فاتورة طلبات بعد تسويتها');need(r.date===day(),'الإلغاء متاح لفواتير اليوم فقط');for(const l of r.lines){const p=s.products.find(x=>x.id===l.productId);p.stock+=l.q;p.value+=l.cost;}r.voided=true;r.voidDate=day();}
 function report(s,date){const rows=s.sales.filter(x=>x.date===date&&!x.voided);const sum=(a,k)=>a.reduce((n,x)=>n+x[k],0);const exp=s.expenses.filter(x=>x.date===date),w=s.waste.filter(x=>x.date===date);const purchases=s.purchases.filter(x=>x.date===date);const totals={};for(const k of ['cash','visa','master','talabat'])totals[k]=sum(rows.filter(x=>x.payment===k),'total');return {rows,totals,sales:sum(rows,'total'),fees:sum(rows,'fee'),cost:sum(rows,'cost'),expenses:sum(exp,'total'),waste:sum(w,'cost'),purchases:sum(purchases,'total'),profit:sum(rows,'net')-sum(rows,'cost')-sum(exp,'total')-sum(w,'cost'),cash:totals.cash-sum(exp.filter(x=>x.payment==='cash'),'total')-sum(purchases.filter(x=>x.payment==='cash'),'total'),due:sum(s.sales.filter(x=>!x.voided&&x.payment==='talabat'&&!s.settlements.some(t=>t.saleId===x.id)),'net'),inventory:sum(s.products,'value')};}
 return {day,id,money,qty,fresh,validate,addProduct,buy,sell,waste,voidSale,report,need};
})();
