import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';
const context=vm.createContext({crypto:webcrypto,Intl,Date,structuredClone});vm.runInContext(fs.readFileSync('src/core.js','utf8')+';globalThis.core=MF;',context);const C=context.core;
let s=C.fresh();C.addProduct(s,'بندورة','kg',750);C.addProduct(s,'بطيخ','piece',2000);const p=s.products[0],piece=s.products[1];C.buy(s,p.id,10000,5000,'cash','السوق');C.buy(s,p.id,10000,7000,'visa','السوق');assert.equal(p.stock,20000);assert.equal(p.value,12000);
const sale=C.sell(s,[{productId:p.id,q:1250,price:750}],'talabat',25,'123');assert.equal(sale.total,938);assert.equal(sale.cost,750);assert.equal(sale.fee,235);assert.equal(sale.net,703);assert.equal(p.stock,18750);assert.equal(p.value,11250);p.price=1200;assert.equal(sale.lines[0].price,750);
C.waste(s,p.id,1000,'تالف');assert.equal(p.value,10650);assert.equal(s.waste[0].cost,600);s.expenses.push({id:C.id(),date:C.day(),total:1000,payment:'cash',note:'نقل'});assert.equal(C.report(s,C.day()).profit,-1647);assert.equal(C.report(s,C.day()).cash,-6000);assert.equal(C.report(s,C.day()).due,703);C.validate(s);
assert.throws(()=>C.buy(s,piece.id,1500,1000,'cash',''),/الحبة/);const clone=structuredClone(s);assert.throws(()=>C.sell(clone,[{productId:p.id,q:999999,price:750}],'cash',0,''),/المخزون/);assert.equal(clone.products[0].stock,s.products[0].stock);
C.voidSale(s,sale.id);assert.equal(p.stock,19000);assert.equal(p.value,11400);assert.equal(C.report(s,C.day()).sales,0);assert.equal(C.report(s,C.day()).profit,-1600);assert.throws(()=>C.voidSale(s,sale.id));assert.throws(()=>C.validate({...s,schema:2}));
const malformed=structuredClone(s);malformed.products[0].value=-1;assert.throws(()=>C.validate(malformed));const all=C.sell(s,[{productId:p.id,q:p.stock,price:1000}],'cash',0,'');assert.equal(p.value,0);assert.equal(p.stock,0);C.validate(s);
// Validate built inline JS and a supported modelContext read call in a controlled DOM harness.
let registered;const html=fs.readFileSync('../Momen-Fresh.html','utf8');const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);const nodes=new Map();const node=id=>nodes.get(id)||nodes.set(id,{id,innerHTML:'',textContent:'',value:'',disabled:false,style:{},classList:{add(){},remove(){}},insertAdjacentHTML(){}}).get(id);const ls=new Map();const browser=vm.createContext({crypto:webcrypto,Intl,Date,structuredClone,console,URL,Blob,localStorage:{getItem:k=>ls.get(k)||null,setItem:(k,v)=>ls.set(k,v)},document:{getElementById:node,activeElement:null,modelContext:{registerTool(t){registered=t;}},createElement:()=>({click(){}})},location:{protocol:'file:'},navigator:{onLine:false},window:{addEventListener(){},showDirectoryPicker:null},setTimeout:()=>0,clearTimeout(){},confirm:()=>true,indexedDB:{open(){throw Error('not supported');}}});for(const code of scripts)vm.runInContext(code,browser);assert.equal(registered.name,'read_shop_summary');assert.equal(registered.annotations.readOnlyHint,true);assert.equal(registered.execute({date:C.day()}).sales,0);assert.throws(()=>registered.execute({date:'bad'}));vm.runInContext("setTab('prices');setTab('stock');setTab('expenses');setTab('reports');setTab('backup');setTab('pos');",browser);
// Exercise owner-private API, CAS conflict and archived recovery using an in-memory R2 contract.
const worker=(await import('./dist/server/index.js')).default;let serial=0;const objects=new Map();const bucket={async get(key){const o=objects.get(key);return o?{...o,json:async()=>JSON.parse(o.data)}:null;},async head(key){const o=objects.get(key);return o?{etag:o.etag}:null;},async put(key,data,opt={}){const cur=objects.get(key),cond=opt.onlyIf;if(cond){const match=cond.get('If-Match'),none=cond.get('If-None-Match');if(match&&(!cur||'"'+cur.etag+'"'!==match))return null;if(none==='*'&&cur)return null;}const o={key,data,etag:'v'+(++serial),uploaded:new Date()};objects.set(key,o);return o;},async list({prefix,limit}){return {objects:[...objects.values()].filter(x=>x.key.startsWith(prefix)).sort((a,b)=>a.key.localeCompare(b.key)).slice(0,limit)};}};const env={BUCKET:bucket};const request=(path,method='GET',body,auth=true)=>new Request('https://shop.example'+path,{method,headers:{...(auth?{'oai-authenticated-user-id':'owner'}:{}),...(body?{'Content-Type':'application/json','Origin':'https://shop.example'}:{})},...(body?{body:JSON.stringify(body)}:{})});
assert.equal((await worker.fetch(request('/api/state','GET',null,false),env,{})).status,401);assert.equal(objects.size,0);let get=await (await worker.fetch(request('/api/state'),env,{})).json();assert.equal(get.state,null);const data=C.fresh();const save=await worker.fetch(request('/api/state','PUT',{etag:null,state:data}),env,{});assert.equal(save.status,200);const ack=await save.json();assert.equal(ack.archive,true);assert.equal((await worker.fetch(request('/api/state','PUT',{etag:null,state:data}),env,{})).status,409);get=await (await worker.fetch(request('/api/state'),env,{})).json();assert.equal(get.etag,ack.etag);assert.equal(get.state.store,'مؤمن فريش');const history=await (await worker.fetch(request('/api/history'),env,{})).json();assert.equal(history.items.length,1);const recovered=await (await worker.fetch(request('/api/snapshot?key='+encodeURIComponent(history.items[0].key)),env,{})).json();assert.equal(recovered.state.store,'مؤمن فريش');const next=structuredClone(data);next.revision++;const pair=await Promise.all([worker.fetch(request('/api/state','PUT',{etag:ack.etag,state:next}),env,{}),worker.fetch(request('/api/state','PUT',{etag:ack.etag,state:next}),env,{})]);assert.deepEqual(pair.map(r=>r.status).sort(),[200,409]);assert.equal((await worker.fetch(request('/api/state','PUT',{etag:ack.etag,state:{schema:2}}),env,{})).status,400);assert.equal((await worker.fetch(request('/'),env,{})).headers.get('X-Momen-App'),'1');console.log('PASS: money, stock costing, fees, waste, void, validation, six UI views, WebMCP read, private API, CAS concurrency, archives');
